### ISSUE TITLE
Plugin with id 'kotlin-android-extensions' not found.

### ISSUE THREAD

**Issue by dwaindibbly** [rbcprolabs/native_pdf_renderer#1]
i transfered from the other plugin... native_pdf_view... and uhh.
i'm using java on the android side.

**Comment by SergeShkurko** [comment]
@dwaindibbly if you can't won't open project in android studio - 
select dir: `./example/android`
instead: `./android`

**Comment by dwaindibbly** [comment]
I...
I'm using Visual Studio Code.
And what kind of sentence is that?

**Comment by dwaindibbly** [comment]
ok if i add
`classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"` and `ext.kotlin_version = '1.3.21'` lines to build.gradle then the original error is fixed but then i get a new error from flutter itself

**Comment by SergeShkurko** [comment]
show logs please

**Comment by dwaindibbly** [comment]
well... there are no logs but there is this: `MissingPluginException (MissingPluginException(No implementation found for method SystemChrome.setApplicationSwitcherDescription on channel flutter/platform))`

**Comment by dwaindibbly** [comment]
i think the way to reproduce the error is by creating a flutter project (using java) and importing the native_pdf_renderer

**Comment by dwaindibbly** [comment]
ok, will try now

**Comment by SergeShkurko** [comment]
I checked with pure Java project and add `classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"` will improve  bug
Thanks
Version bumped to `1.1.1`

**Comment by dwaindibbly** [comment]
Works!
